/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExcluirContaRouteImport } from './routes/excluir-conta'
import { Route as InstalarAppRouteImport } from './routes/instalar-app'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SegurancaDadosRouteImport } from './routes/seguranca-dados'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated/assinaturas'
import { Route as AuthenticatedBarbeirosRouteImport } from './routes/_authenticated/barbeiros'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedHorariosRouteImport } from './routes/_authenticated/horarios'
import { Route as AuthenticatedLinkRouteImport } from './routes/_authenticated/link'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as BarbeariaSlugRouteImport } from './routes/barbearia.$slug'
import { Route as ApiPublicBillingPixWebhookRouteImport } from './routes/api/public/billing/pix-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcluirContaRoute = ExcluirContaRouteImport.update({
  id: '/excluir-conta',
  path: '/excluir-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarAppRoute = InstalarAppRouteImport.update({
  id: '/instalar-app',
  path: '/instalar-app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaDadosRoute = SegurancaDadosRouteImport.update({
  id: '/seguranca-dados',
  path: '/seguranca-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBarbeirosRoute = AuthenticatedBarbeirosRouteImport.update({
  id: '/barbeiros',
  path: '/barbeiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHorariosRoute = AuthenticatedHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkRoute = AuthenticatedLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BarbeariaSlugRoute = BarbeariaSlugRouteImport.update({
  id: '/barbearia/$slug',
  path: '/barbearia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingPixWebhookRoute =
  ApiPublicBillingPixWebhookRouteImport.update({
    id: '/api/public/billing/pix-webhook',
    path: '/api/public/billing/pix-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/instalar-app': typeof InstalarAppRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca-dados': typeof SegurancaDadosRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/barbeiros': typeof AuthenticatedBarbeirosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/link': typeof AuthenticatedLinkRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/barbearia/$slug': typeof BarbeariaSlugRoute
  '/api/public/billing/pix-webhook': typeof ApiPublicBillingPixWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/instalar-app': typeof InstalarAppRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca-dados': typeof SegurancaDadosRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/barbeiros': typeof AuthenticatedBarbeirosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/link': typeof AuthenticatedLinkRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/barbearia/$slug': typeof BarbeariaSlugRoute
  '/api/public/billing/pix-webhook': typeof ApiPublicBillingPixWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/instalar-app': typeof InstalarAppRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca-dados': typeof SegurancaDadosRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/_authenticated/barbeiros': typeof AuthenticatedBarbeirosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/horarios': typeof AuthenticatedHorariosRoute
  '/_authenticated/link': typeof AuthenticatedLinkRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/barbearia/$slug': typeof BarbeariaSlugRoute
  '/api/public/billing/pix-webhook': typeof ApiPublicBillingPixWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/auth'
    | '/dashboard'
    | '/excluir-conta'
    | '/instalar-app'
    | '/privacidade'
    | '/seguranca-dados'
    | '/suporte'
    | '/termos'
    | '/agenda'
    | '/assinaturas'
    | '/barbeiros'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/horarios'
    | '/link'
    | '/marketing'
    | '/onboarding'
    | '/planos'
    | '/servicos'
    | '/barbearia/$slug'
    | '/api/public/billing/pix-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/auth'
    | '/dashboard'
    | '/excluir-conta'
    | '/instalar-app'
    | '/privacidade'
    | '/seguranca-dados'
    | '/suporte'
    | '/termos'
    | '/agenda'
    | '/assinaturas'
    | '/barbeiros'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/horarios'
    | '/link'
    | '/marketing'
    | '/onboarding'
    | '/planos'
    | '/servicos'
    | '/barbearia/$slug'
    | '/api/public/billing/pix-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agendar'
    | '/auth'
    | '/dashboard'
    | '/excluir-conta'
    | '/instalar-app'
    | '/privacidade'
    | '/seguranca-dados'
    | '/suporte'
    | '/termos'
    | '/_authenticated/agenda'
    | '/_authenticated/assinaturas'
    | '/_authenticated/barbeiros'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/financeiro'
    | '/_authenticated/horarios'
    | '/_authenticated/link'
    | '/_authenticated/marketing'
    | '/_authenticated/onboarding'
    | '/_authenticated/planos'
    | '/_authenticated/servicos'
    | '/barbearia/$slug'
    | '/api/public/billing/pix-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExcluirContaRoute: typeof ExcluirContaRoute
  InstalarAppRoute: typeof InstalarAppRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SegurancaDadosRoute: typeof SegurancaDadosRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  BarbeariaSlugRoute: typeof BarbeariaSlugRoute
  ApiPublicBillingPixWebhookRoute: typeof ApiPublicBillingPixWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excluir-conta': {
      id: '/excluir-conta'
      path: '/excluir-conta'
      fullPath: '/excluir-conta'
      preLoaderRoute: typeof ExcluirContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar-app': {
      id: '/instalar-app'
      path: '/instalar-app'
      fullPath: '/instalar-app'
      preLoaderRoute: typeof InstalarAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca-dados': {
      id: '/seguranca-dados'
      path: '/seguranca-dados'
      fullPath: '/seguranca-dados'
      preLoaderRoute: typeof SegurancaDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barbeiros': {
      id: '/_authenticated/barbeiros'
      path: '/barbeiros'
      fullPath: '/barbeiros'
      preLoaderRoute: typeof AuthenticatedBarbeirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horarios': {
      id: '/_authenticated/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AuthenticatedHorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/link': {
      id: '/_authenticated/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AuthenticatedLinkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/barbearia/$slug': {
      id: '/barbearia/$slug'
      path: '/barbearia/$slug'
      fullPath: '/barbearia/$slug'
      preLoaderRoute: typeof BarbeariaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/pix-webhook': {
      id: '/api/public/billing/pix-webhook'
      path: '/api/public/billing/pix-webhook'
      fullPath: '/api/public/billing/pix-webhook'
      preLoaderRoute: typeof ApiPublicBillingPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRoute
  AuthenticatedBarbeirosRoute: typeof AuthenticatedBarbeirosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHorariosRoute: typeof AuthenticatedHorariosRoute
  AuthenticatedLinkRoute: typeof AuthenticatedLinkRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRoute,
  AuthenticatedBarbeirosRoute: AuthenticatedBarbeirosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHorariosRoute: AuthenticatedHorariosRoute,
  AuthenticatedLinkRoute: AuthenticatedLinkRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendarRoute: AgendarRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExcluirContaRoute: ExcluirContaRoute,
  InstalarAppRoute: InstalarAppRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SegurancaDadosRoute: SegurancaDadosRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  BarbeariaSlugRoute: BarbeariaSlugRoute,
  ApiPublicBillingPixWebhookRoute: ApiPublicBillingPixWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
